---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nodereadiness.io
  resources:
  - nodereadinessgaterules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodereadiness.io
  resources:
  - nodereadinessgaterules/finalizers
  verbs:
  - update
- apiGroups:
  - nodereadiness.io
  resources:
  - nodereadinessgaterules/status
  verbs:
  - get
  - patch
  - update
