# This file is used to patch default (global) FelixConfiguration to enable healthz endpoint for Calico in all Nodes.
# original calico manifest https://raw.githubusercontent.com/projectcalico/calico/v3.30.1/manifests/calico.yaml
spec:
  healthEnabled: true